// Package indiware2json converts the XML output from Indiware Unterrichtsplaner
// into structured, optimized JSON. It can also output a room plan.
// Currently tested on version 7.
// All code is generated by a brain and handwritten. AI is only used for troubleshooting.
package indiware2json
